Website_Main
DPodgorny/JS2QA pull request #6
Opened 2018-05-11 17:29 UTC by DPodgorny

2018-05-12 20:48 UTC, SergeBondar reviewed
а из какой ветки ты создавал эту?
и нужно добавить парочку пробелов вокруг =

2018-05-12 20:48 UTC, SergeBondar commented on Website/modelDropdownFill.js
> +    var model=[];
models?

2018-05-13 19:22 UTC, DPodgorny commented
Эта ветка сделана из ветки  Task3. Понял свою ошибку, вмержил предыдущий код еще до того как ты аппрувнул. Поскольку изменений там уже нет, то так и оставим.

2018-05-13 19:22 UTC, DPodgorny commented on Website/modelDropdownFill.js
> +    var model=[];
Ну это не принципиально. Могу подправить.

2018-05-14 10:00 UTC, SergeBondar requested changes

2018-05-14 10:00 UTC, SergeBondar commented on Website/index.html
> +</head>
закрывающий тег вначале? это как?

2018-05-14 10:00 UTC, SergeBondar commented on Website/index.html
> +    <script language="JavaScript" type="text/javascript" src="modelList.js"></script>
Language и type можно не писать

2018-05-14 10:13 UTC, SergeBondar approved these changes

2018-05-16 13:52 UTC, MaxMarasanov commented on Website/modelDropdownFill.js
> +    newEl.value = '';
Изначально дроп-даун с моделями не имеет ни одного <option>, если не выбран производитель. Но если выбрать производителя, а потом убрать, то появляется один пустой <option>. Нужно, чтобы было одинаково.

2018-05-16 13:52 UTC, MaxMarasanov commented on Website/modelDropdownFill.js
> +    newEl.value = '';
Плюс вместо пустых начальных значений лучше указывать что-то в стиле "Please select model", "Please select manufacturer" и т.д.

2018-05-17 09:50 UTC, MaxMarasanov approved these changes

2018-05-17 11:46 UTC, merged