Wensite_Generate_Report
DPodgorny/JS2QA pull request #7
Opened 2018-05-14 15:35 UTC by DPodgorny

Finished generate report function

2018-05-16 08:09 UTC, SergeBondar requested changes

2018-05-16 08:09 UTC, SergeBondar commented on Website/generateReport.js
> +    var tableDiv = document.getElementById('tableDiv');
лучше сначала создать переменную, а потом очищать ее

2018-05-16 08:09 UTC, SergeBondar commented on Website/generateReport.js
> +    document.getElementById('tableDiv').innerHTML='';
пробелы

2018-05-16 08:09 UTC, SergeBondar commented on Website/generateReport.js
> +            table.border = '3';
стили не должны быть в js

2018-05-16 08:09 UTC, SergeBondar commented on Website/generateReport.js
> +                modNameLength = mod.length % 2;
весь дублирующийся код надо вынести в отдельную функцию

2018-05-16 08:09 UTC, SergeBondar commented on Website/index.html
> +    <select onchange="fillModelTable(this.value)" id="Manufacturer">
давай добавим <label for=""> для дропдаунов

2018-05-16 08:09 UTC, SergeBondar commented on Website/modelDropdownFill.js
> +var models=[];
пробелы

2018-05-16 08:09 UTC, SergeBondar commented on Website/modelDropdownFill.js
> +    document.getElementById('Model').innerHTML = '';
сначала создаем переменную

2018-05-17 12:19 UTC, MaxMarasanov reviewed
Только не Wensite_Generate_Report, а Website_Generate_Report

2018-05-17 12:52 UTC, SergeBondar approved these changes

2018-05-18 21:53 UTC, SergeBondar requested changes

2018-05-18 21:53 UTC, SergeBondar commented on Website/fillTableFunctions.js
> +    tableDiv.appendChild(table);
это лучше сделать в самом конце

2018-05-18 21:53 UTC, SergeBondar commented on Website/fillTableFunctions.js
> +    var td = document.createElement('td');
th?

2018-05-18 21:53 UTC, SergeBondar commented on Website/generateReport.js
> +    if (manufacturerList.includes(man) === false) {
!

2018-05-18 21:53 UTC, SergeBondar commented on Website/generateReport.js
> +    if (mod != '') {
строгое

2018-05-18 21:53 UTC, SergeBondar commented on Website/generateReport.js
> +            fillTableMod(modelSorted[a]);
addRow?

2018-05-18 21:53 UTC, SergeBondar commented on Website/generateReport.js
> +        fillTableMan(man);
addHeader? createHeader?

2018-05-18 21:53 UTC, SergeBondar commented on Website/modelDropdownFill.js
>  function fillModelTable(modelListLoad) {
fillModelDropDown?

2018-05-21 14:06 UTC, SergeBondar commented on Website/fillTableFunctions.js
> +function addHeader(inputMan) {
по факту это не только addHeader
лучше разделить все же эту логику
и еще лучше сделать ее независимой от классов

2018-05-22 11:54 UTC, DPodgorny commented
Сергей, разобрался с тем, что ты предлагал сделать, немного подправил и залил. Но общий смысл фикса именно тот, как ты и говорил. Если будет интересно, могу потом показать, что у меня в стеше лежит, и что и почему я поменял.

2018-05-22 13:13 UTC, SergeBondar approved these changes
в идеале валидации вынести в отдельную функцию, но в принципе можно и так оставить пока

2018-05-22 14:44 UTC, DPodgorny commented
Need review after latest changes.

2018-05-22 14:59 UTC, SergeBondar commented on Website/validations.js
> +        if (models.includes(mod) === false) {
!

2018-05-22 14:59 UTC, SergeBondar commented on Website/generateReport.js
> +        addHeader(table, man);
ты же все равно это вызываешь
напиши 1 раз после создания таблицы

2018-05-22 15:32 UTC, MaxMarasanov approved these changes

2018-05-22 15:35 UTC, DPodgorny commented
@SergeBondar последний разок)

2018-05-22 15:36 UTC, SergeBondar approved these changes

2018-05-22 15:40 UTC, merged