Styles
DPodgorny/JS2QA pull request #8
Opened 2018-05-15 22:48 UTC by DPodgorny

2018-05-16 08:13 UTC, SergeBondar requested changes

2018-05-16 08:13 UTC, SergeBondar commented on Website/Website.css
> +.buttonP {
что такое buttonP?

2018-05-16 08:13 UTC, SergeBondar commented on Website/Website.css
> +td {
сначала все common стили, по тегу
потом более специфичные - по классу

2018-05-23 08:01 UTC, SergeBondar requested changes

2018-05-23 08:01 UTC, SergeBondar commented on Website/index.html
> +<link>
как это link?

2018-05-23 08:47 UTC, DPodgorny commented on Website/index.html
> +<link>
Опечатка.

2018-05-23 12:41 UTC, SergeBondar commented on Website/index.html
>      <select onchange="fillModelDropDown(this.value)" id="manufacturer">
тут отступ должен значит быть?

2018-05-24 09:25 UTC, SergeBondar approved these changes

2018-05-24 14:31 UTC, MaxMarasanov approved these changes

2018-05-24 15:13 UTC, merged